os:
  - linux
  - osx
sudo: false
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  matrix:
    - TRAVIS_NODE_VERSION="8"
    - TRAVIS_NODE_VERSION="6.11"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Node 0.8 comes with a too obsolete npm
  - if [[ "`node --version`" =~ ^v0\.8\. ]]; then npm install -g npm@1.4.28 ; fi
  # Install dependencies and build
  - npm install

script:
  - node --version
  - npm --version
  - npm test

SET NODE_PRE_GYP_GITHUB_TOKEN=aaef4f5d3c63bcc37b57e9eecea5f4c3c8415aa6
export NODE_PRE_GYP_GITHUB_TOKEN=aaef4f5d3c63bcc37b57e9eecea5f4c3c8415aa6

npm install --build-from-source
./node_modules/.bin/node-pre-gyp package
node-pre-gyp-github publish --release
node-pre-gyp-github publish

