# http://www.appveyor.com/docs/appveyor-yml


environment:
  MSVS_VERSION: 2013
  NODE_PRE_GYP_GITHUB_TOKEN: "aaef4f5d3c63bcc37b57e9eecea5f4c3c8415aa6"
  matrix:
    - nodejs_version: "8"
#    - nodejs_version: "6.11"

platform:
  - x86
#  - x64


install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --build-from-source --msvs_version=%MSVS_VERSION%
#  SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
#  if not "%CM%" == "%CM:[publish binary]=%" node-pre-gyp-github --msvs_version=2013 publish

  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('publish binary')) { node-pre-gyp-github --msvs_version=2013 publish }

test_script:
  - node --version
  - npm --version
  - npm test

build: off

version: "{build}"
